### ISSUE TITLE
requirement clip==1.0 causing installation failure

### ISSUE THREAD

**Issue by dgstrmn** [yanghb22-fdu/Hi3D-Official#1]
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0

failed

CondaEnvException: Pip failed

**Comment by yanghb22-fdu** [comment]
pip install git+https://github.com/openai/CLIP.git
I strongly recommend that you follow the installation instructions in this repository: https://github.com/Stability-AI/generative-models
