### ISSUE TITLE
Training is stalling

### ISSUE THREAD

**Issue by jeffeDurand** [yanghb22-fdu/Hi3D-Official#12]
Hi, thanks for opening this amazing project. I was using syncdreamer until now and was looking at having a 1024 resolution inference instead.

I have generated my 96 frames 1024x1024 using a modified syncdreamer blender script that I feel is comparable to the training set that is in the example from the project's readme doc. (see my pull requests if you want to have it freely in your project for others)

I have downloaded svd_xt_image_decoder.safetensors, and the ckpts package and updated the train config file location with it as per instructions

I've changed the environments file to remove all errors/warnings and things that aren't under a proper pip repos (sdata/sgm) and remove the tinycuda not necessary for the project. I can add this to a pull request if needed. I've joined the file here.

I have tried a couple of things, but the current training is always at :

[09/25 20:11:58 VTDM]: Epoch: 0, batch_num: inf
/home/ubuntu/Hi3D-Official/.conda/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:56: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(

and it never gets to do anything else. There's no warning above that would tell something is wrong in my setup. I've joined my train file and logs along my environment file. I'm running the training on a A100. Can you help me get pass this and have the training working?

[environments.txt](https://github.com/user-attachments/files/17138103/environments.txt)
[train-v01.txt](https://github.com/user-attachments/files/17138104/train-v01.txt)
[Hi3D_Train_Logs.txt](https://github.com/user-attachments/files/17138066/Hi3D_Train_Logs.txt)

**Comment by yanghb22-fdu** [comment]
Thank you for your attention. I haven't encountered a similar issue during my training. I've reviewed your log, and it seems everything was going well at the beginning. Have you tried debugging to pinpoint exactly which line of code the experiment is getting stuck on?
This is my [pip list](https://huggingface.co/hbyang/Hi3D/blob/main/piplist.txt).  you can check it and see if there are any discrepancies or missing packages that could be causing the problem?

**Comment by yanghb22-fdu** [comment]
I noticed that there is a warning related to xformers at the start of my experiment. Could you please check if you have installed the version of xformers that corresponds to your CUDA and PyTorch versions? This might be causing the issue. Below is my training log start:
```
python train_ddp_spawn.py \
>     --base configs/train-v01.yaml \
>     --no-test True \
>     --train True \
>     --logdir outputs/logs/train-v01
[2024-09-26 12:49:56,509] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
2024-09-26 12:50:05.896497: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-26 12:50:06.077771: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-26 12:50:06.663935: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-26 12:50:08.970339: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Global seed set to 2300
[09/26 12:50:16 VTDM]: Running on GPUs 7,
[09/26 12:50:16 VTDM]: Use the strategy of deepspeed_stage_2
[09/26 12:50:16 VTDM]: Pytorch lightning trainer config: 
{'gpus': '7,', 'logger_refresh_rate': 50, 'check_val_every_n_epoch': 1, 'max_epochs': 50, 'accelerator': 'cuda', 'strategy': 'deepspeed_stage_2', 'precision': 16}
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
```

**Comment by jeffeDurand** [comment]
For these warnings:

```
[WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 ```

 I've removed some by doing:
 
 sudo apt install libaio-dev
 
on my A100 since I tought it was a problem at first.

I've also updated triton to 2.1.0 to remove the other warning. 

And I also compiled xformers 0.22 within my conda env using your git tag and my current env pytorch 2.0.1 while making sure it is compatible to remove the rest. Nothing of this helped.

I've tried installing all your dependencies with cuda 11.8, but also tried to use pytorch 2.1.x with cuda 12.2 and recompiling pytorch3d/xformers/tinycudann/torchdata within the projects.

Here's my conda env + python requirement file I have use for cuda 12.2. I've also joined the new logs for it.

[environments.txt](https://github.com/user-attachments/files/17172167/environments.txt)
[requirements.txt](https://github.com/user-attachments/files/17172115/requirements.txt)
[logs_cuda122.txt](https://github.com/user-attachments/files/17172180/logs_cuda122.txt)

Rename environments.txt to .yaml since github doesn't support them in issues.

For both scenario, it just ends doing nothing at epoch 0 after the call to trainer.fit(...). I've monitored the gpustats with nvidia-smi and I'm far from lacking gpu memory on my A100 at any point during the training script.

What I have seen in your piplist that I'm not sure about is this :

`sgm @ file:///mnt/afs_intern/yanghaibo/codes/generative-models`

What is this library and should it be installed for the solution to work? If then, where does it come from?

Or is there anything else you can think of that is not written in your project's setup and that is custom to your experiment? Have you tried rebuilding your env yourself on a new setup and it still works?

**Comment by jeffeDurand** [comment]
Also, can you send me your entire log for the experiment so that I can check for other difference on my running attempt?

**Comment by yanghb22-fdu** [comment]
Hello, as I mentioned in the README, my entire project is a modification starting from https://github.com/Stability-AI/generative-models. Therefore, I initially followed this repository to install the dependencies, including sgm, based on the instructions within that repository, as shown in the tutorial below. 
![Screenshot from 2024-09-29 13-25-04](https://github.com/user-attachments/assets/e9f46222-b4ff-489c-9937-1c13a0f6e980)
Theoretically, if you can run the toy training code provided by generative-models, the environment should be directly usable for Hi3D. I have placed my complete example training log [here](https://huggingface.co/hbyang/Hi3D/blob/main/log.txt). If possible, you can debug your code and tell me exactly where your code is getting stuck.

**Comment by jeffeDurand** [comment]
Thanks for the reply. I've looked at your logs and configs and didn't find anything suspicious to help me with the actual behaviour.

I have tried to assemble my env with only https://github.com/Stability-AI/generative-models with their requirements, but it seems that their pt2.txt would install pytorch-lightning>=2 which your project won't run with (also missing cupy, test-tube and deepspeed==0.14.2). I've manually installed these libraries, but it still get a stalling state from either inference or training. I will now try to run inference and training for generative-models to see if I can get it to work versus Hi3D.

For the moment, I've never been able to run inference nor start training with this project.

**Comment by jeffeDurand** [comment]
I've finally managed to run inference on a h100 with a tweaked conda environment, pytorch 2.1, pytorch-lightning 1.9, triton 2.1 and cuda 12.1. I'll try now to run the training with my custom data

**Comment by jeffeDurand** [comment]
I've managed to update the project to work on my h100 machine. I can now start the training. I could open a merge request my the new code to support both the a100 and the h100 (cuda arch sm_90) if you want. The setup would be much simpler with only one conda environment call.

Thanks for the help.

**Comment by HardikJain02** [comment]
@jeffeDurand please share your steps for inference with environments.yaml, pt2.txt, and custom pip install.

**Comment by jeffeDurand** [comment]
See pull request : https://github.com/yanghb22-fdu/Hi3D-Official/pull/6
