### ISSUE TITLE
Can the model be uploaded to HuggingFace?

### ISSUE THREAD

**Issue by chenbinghui1** [yanghb22-fdu/Hi3D-Official#2]
HuggingFace is more efficient for downloading large models!

**Comment by yanghb22-fdu** [comment]
Hi, I have uploaded all the checkpoints to Hugging Face: https://huggingface.co/hbyang/Hi3D/tree/main

**Comment by NielsRogge** [comment]
Great (Niels here from HF!). I opened a PR to improve it: https://huggingface.co/hbyang/Hi3D/discussions/1.

Also, would it be possible to mention the Hugging Face model repo in the README of this Github repo?
