### ISSUE TITLE
About finetune model

### ISSUE THREAD

**Issue by zbtzbt44** [yanghb22-fdu/Hi3D-Official#21]
Thanks for your excellent eork!I have a problem with finetuning the model("first stage.pt").When I train with the vanilla SVD model,I can get the following 2 model weights."mp_rank_00_model_states.pt" has the same size as "first stage.pt",but I cannot get the "zero_pp_rank_0_mp_rank_00_optim_states.pt" matching the "first stage.pt".
Therefore,if I want to finetune the model with more datasets,I replace "first stage.pt" with "mp_rank_00_model_states.pt",but how to get the "zero_pp_rank_0_mp_rank_00_optim_states.pt"?
![image](https://github.com/user-attachments/assets/b9b554ec-6680-4b7c-bfb7-9e35baff82c9)

**Comment by zbtzbt44** [comment]
I solve it.Just the first weight is OK.

**Comment by 2hiTee** [comment]
> I solve it.Just the first weight is OK.

Hi, so if I fine-tuned the model, which one should I use for inference? or continue fituning? Thank you!

**Comment by qwera-wqw** [comment]
> > I solve it.Just the first weight is OK.
> 
> Hi, so if I fine-tuned the model, which one should I use for inference? or continue fituning? Thank you!

Based on my experience, it's the first one.

**Comment by 2hiTee** [comment]
I also have managed it. Thanks for your reply!

---- Replied Message ----
| From | wenqiang ***@***.***> |
| Date | 11/28/2024 15:30 |
| To | yanghb22-fdu/Hi3D-Official ***@***.***> |
| Cc | 2hiTee ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [yanghb22-fdu/Hi3D-Official] About finetune model (Issue #21) |

I solve it.Just the first weight is OK.

Hi, so if I fine-tuned the model, which one should I use for inference? or continue fituning? Thank you!

Based on my experience, it's the first one.
