### ISSUE TITLE
Quantifying results

### ISSUE THREAD

**Issue by jspsiy** [yanghb22-fdu/Hi3D-Official#23]
Hello, 

I have some questions:

1)How did you get the comparative results (LPIPS, PSNR etc.. )? Hi3D only produces 16 images for elevation 0 right? So given we have syncdreamer's dataset that starts from iamge 0 ~ 95. did you just compare iamge 16~image 31 for elevation 0 or you produced 6 videos and compared them with the whole testing data folder for the first image? Take exxample did you take the LPIPS of image 1 and LPIPS of image 2 then averaged them?

**Comment by yanghb22-fdu** [comment]
Hi, Hi3D can accept elevation as a conditional input during inference (e.g., 0 or 30), so our test results are strictly aligned with the settings of [Syncdreamer](https://github.com/liuyuan-pal/SyncDreamer/issues/51).

**Comment by jspsiy** [comment]
Oh. Thank you!
